// File generated by FlutterFire CLI.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaI_vKLUE47uuQTFqm7QRvpwnBP_gu4bQ',
    appId: '1:462780399509:android:53a53c5d78bee3c52b009c',
    messagingSenderId: '462780399509',
    projectId: 'savvy-cffb8',
    storageBucket: 'savvy-cffb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCgfNJhSu-UgOTY2h9A58tq3VV1siPP1c',
    appId: '1:462780399509:ios:65c610a3708d9eed2b009c',
    messagingSenderId: '462780399509',
    projectId: 'savvy-cffb8',
    storageBucket: 'savvy-cffb8.firebasestorage.app',
    iosBundleId: 'com.savvy.savvy',
  );

}